### ISSUE TITLE
Issue with your Media Object + List Group code .. help?

### ISSUE THREAD

**Issue by vongoh** [algonquindesign/html-css#3]
HI - I've been working through your thoroughly awesome and helpful YouTube tutorials - in particular learning the practical application of OOCSS modules - such as the media object.   Great job!  I'm finally getting my head around it after countless poor explanations before this,  thanks so much

However - I have run into an issue with getting your code to work, when combining the media object with list group.   It seems that the `overflow: hidden` on the inner `media__body` is truncating off the titles of the list items.

Here is a link to the Codepen:
http://codepen.io/vongoh/pen/VYxLKw

.. where you will see what I am talking about right away.  Advice?  Thanks .. 

Also - FYI:

In your media object video you decided not to use a class for the `media__body__text`.  It turns out the media object will not square up nicely unless you do -- and particularly for this media object + list-group pattern.   If I did not add the following code:

~~~scss
.media__body__text {
    margin: 0;
}
~~~
~~~html5
<p class="media__body__text">Item</p>
~~~
.. then the item titles in the list group media objects would not just be truncated,  they come out way out of line *and* truncated.   Again,  FYI ... 

~~~

**Comment by thomasjbradley** [comment]
Thanks for submitting an issue.

But, I can’t really see what you mean, could you maybe send a screenshot of what you’re seeing?

**Comment by vongoh** [comment]
[Imgur](http://i.imgur.com/CYZsezP.png)

**Comment by thomasjbradley** [comment]
That’s a really weird bug—and seems to only happen in Firefox.

I don’t have a definite reason for why it’s happening, but do have a solution:
On the `.media__body` elements inside the `.list-group` if you apply `float: left`, they seem to work properly.

It’s a work around that solves the problem, but I don’t understand why the problem is happening to begin with.

**Comment by vongoh** [comment]
Thanks!   Unless you can think of a more elegant solution, this seems to do the trick:

~~~scss
// List Group CSS
.list-group {
   padding: 0;
	display: block;
   list-style-type: none;
}

.list-group--inline {
	display: inline-block;
}
    
    .list-group__item {
    	display: block;
    }

	// Needed for Firefox bug affecting media objects inside of list-groups	
	 .list-group__item .media__body {
		 float: left;
	 }

    .list-group__item--inline {
		 width: auto;
    	 display: inline-block;
    }

    /* In case custom bullets are used */
    .list-group__item::before {
    	content: none;
    }
~~~
